### ISSUE TITLE
Undefined References

### ISSUE THREAD

**Issue by rdob** [armadillu/ofxTurboJpeg#4]
Dear All,

I can't get it run, I have undefined references to I guess libtubojpeg. The last version of libturbojpeg is installed LD Path included, and no chance to get it run, pls help

e.g.
ofxTurboJpeg.cpp(.text+0x8): undefined reference to 'tjInitCompress'

**Comment by armadillu** [comment]
make sure you set the project library paths include a path to the lib, and also that you include the dylib in the "link binary with libraries" build phase (on Xcode at least)
