### ISSUE TITLE
osx dylib is 4 years old

### ISSUE THREAD

**Issue by ofZach** [armadillu/ofxTurboJpeg#7]
not sure if this is an issue but the osx lib seems quite old....   ping @mattfelsen since it seems like you've been using this recently.

**Comment by mattfelsen** [comment]
Hey Zach! Old indeed...it *is* a fat lib and I'm currently using it in a 64-bit project on OS X without issue

```
$ lipo -info libturbojpeg.dylib 
Architectures in the fat file: libturbojpeg.dylib are: i386 x86_64 
```

Are there some newer features in libjpeg-turbo that you need which aren't available in this version? To be honest I have no idea what version it is, but for simply loading jpegs faster than FreeImage/ofLoadImage it's been fine for me

**Comment by ofZach** [comment]
I have no idea if there are improvements, but just thought that potentially there might be some speed optimizations / etc  that might be good to take advantage of as turbo-jpeg seems to be an active project....  (also, I have no idea if there are just feels like if speed is the name of the game, trying the latest and seeing if it helps can't hurt)

**Comment by armadillu** [comment]
I did not build it so I'm not sure how new it is, but there is now a 32/64 bit OSX dylib that seems recent so I'l close this for for now
